### ISSUE TITLE
您好，可以问您一下算法的参考论文吗

### ISSUE THREAD

**Issue by Horizon1997** [Mydawn2/CLkey#1]
如题，十分感谢您！~

**Comment by Mydawn2** [comment]
程朝晖的《基于SM2的无证书加密算法》




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mydawn2/CLkey"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月12日(星期天) 晚上9:18
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Mydawn2/CLkey] 您好，可以问您一下算法的参考论文吗 (#1)





 
如题，十分感谢您！~

**Comment by Horizon1997** [comment]
谢谢！~
